general: 
  experiment_name: 'advection_experiment'
  mode: 'hybrid' # Options: 'physical', 'synthetic', 'hybrid'
  tasks: ['generate', 'train', 'evaluate']

data:
  data_dir: 'data/advection'
  dset_name: 'advection'
  num_simulations: 6
  trajectory_length: 100

model:
  physical:
    name: 'AdvectionModel'
    model_path: 'results/models'
    model_save_name: 'advection_physical_model'
    domain:
      dimensions:
        x: {size: 100, resolution: 128}
        y: {size: 100, resolution: 128}
    dt: 0.05
    pde_params:
      name: 'advection_coeff'
      type: 'scalar'
      value: '0.2'  # Scalar advection coefficient
    modulation:
      enabled: true
      amplitude: 1
      lobes: 6
  synthetic:
    name: 'UNet'
    model_path: 'results/models'
    model_save_name: 'advection_synthetic_model'
    static_fields: ['vel_x', 'vel_y']  # Velocity is static (passed through, not predicted)
    architecture:
      levels: 4
      filters: 64
      batch_norm: false

trainer:
  batch_size: 64
  rollout_steps: 5
  train_sim: [0]  # Use all 6 simulations for more diverse data
  device: 'cuda:0'
  data_access: 'both'
  physical:
    epochs: 1
    rollout_steps: 1
    downsample_factor: 1
    method: 'L-BFGS-B'
    abs_tol: 1e-6
    max_iterations: 10
  synthetic:
    epochs: 10
    rollout_scheduler:
      start: 1
      end: 6
      strategy: 'exponential'
      exponent: 3.0
    learning_rate: 0.0001  # Higher LR with MSE loss
    optimizer: 'adam'
    scheduler: 'cosine'
    weight_decay: 0.0
  hybrid:
    cycles: 10
    warmup: 1
    augmentation:
      alpha: 1.0
      cache_dir: data/cache_phiml  # PhiML cache uses .npz format

    # NEW: Loss scaling configuration
    loss_scaling:
      synthetic:
        real_weight: 1.0        # L coefficient
        interaction_weight: 1.0  # I coefficient
        proportional: false      # Auto-scale I to match L magnitude
      
      physical:
        real_weight: 1.0
        interaction_weight: 0.1  # Physical model sees weaker interaction loss
        proportional: true       # Or use proportional scaling


# For evaluation
evaluation:
  # Which simulations to evaluate
  test_sim: [0]
  
  # Model checkpoint to evaluate
  synthetic_checkpoint: "results/models/advection_synthetic_model.pth"
  physical_checkpoint: "results/models/advection_physical_model.npz"
  
  # How many timesteps to rollout
  num_frames: 100
  
  # Output directory
  output_dir: "results/evaluation/advection"
  
  # Visualization settings
  visualization:
    format: "gif"  # or "mp4"
    fps: 10
    dpi: 100
      
