# Quick test for hybrid training with advection problem
defaults:
  - data: advection_128
  - model/physical: advection
  - model/synthetic: unet_advection
  - trainer: hybrid
  - _self_

run_params:
  experiment_name: 'advection_hybrid_quick_test'
  notes: 'Quick test of hybrid training with pure advection dynamics'
  mode: ['train']
  model_type: 'hybrid'

model:
  synthetic:
    model_save_name: 'advection_hybrid_quick_test'

trainer_params:
  train_sim: [0, 1]  # Use 2 simulations for quick test
  val_sim: []
  epochs: 2  # Very short for quick test
  num_predict_steps: 3
  batch_size: 8
  
  # Hybrid-specific parameters
  hybrid:
    num_cycles: 2  # Just 2 alternating cycles for quick test
    synthetic_epochs_per_cycle: 1
    physical_epochs_per_cycle: 1
    warmup_synthetic_epochs: 0  # Skip warmup for speed
  
  # Augmentation settings
  augmentation:
    alpha: 0.3  # 30% generated, 70% real
    cache:
      enabled: false  # Disable cache for quick test
    on_the_fly:
      rollout_steps: 5
  
  # Synthetic model training settings
  synthetic:
    learning_rate: 1e-4
    optimizer: adam
  
  # Physical model training settings
  physical:
    method: 'L-BFGS-B'
    abs_tol: 1e-6
    max_iterations: 10  # Increased for learning advection_coeff
    suppress_convergence_errors: true
  
  # Learnable parameters for physical model
  learnable_parameters:
    - name: 'advection_coeff'
      initial_guess: 0.8  # Start with 0.8, true value is 1.0
      bounds: [0.1, 2.0]  # Reasonable bounds for advection coefficient

project_root: ${hydra:runtime.cwd}
