general: 
  experiment_name: 'advection_experiment'
  mode: 'synthetic' # Options: 'physical', 'synthetic', 'hybrid'
  tasks: ['generate', 'train', 'evaluate']

data:
  data_dir: 'data/advection'
  dset_name: 'advection'
  num_simulations: 6
  trajectory_length: 100

model:
  physical:
    name: 'AdvectionModel'
    model_path: 'results/models'
    model_save_name: 'advection_physical_model'
    domain:
      dimensions:
        x: {size: 100, resolution: 128}
        y: {size: 100, resolution: 128}
    dt: 0.1
    pde_params:
      name: 'advection_coeff'
      type: 'scalar'
      value: '0.5'  # Scalar advection coefficient
  synthetic:
    name: 'UNet'
    model_path: 'results/models'
    model_save_name: 'advection_synthetic_model'
    static_fields: ['vel_x', 'vel_y']  # Velocity is static (passed through, not predicted)
    architecture:
      levels: 4
      filters: 64
      batch_norm: false

trainer:
  batch_size: 16
  rollout_steps: 4
  train_sim: [0]  # Use all 6 simulations for more diverse data
  device: 'cuda:0'
  data_access: 'both'
  physical:
    epochs: 1
    rollout_steps: 4
    downsample_factor: 0
    learnable_parameters:
      - name: 'advection_coeff'
        type: 'scalar'
        initial_guess: 0.5
    method: 'L-BFGS-B'
    abs_tol: 1e-4
    max_iterations: 5
  synthetic:
    epochs: 2000
    rollout_steps: 4
    learning_rate: 0.0001  # Higher LR with MSE loss
    optimizer: 'adam'
    scheduler: 'cosine'
    weight_decay: 0.0
  hybrid:
    cycles: 10
    warmup: 1
    augmentation:
      alpha: 1.0
      cache_dir: data/cache_phiml  # PhiML cache uses .npz format


# For evaluation
evaluation:
  # Which simulations to evaluate
  test_sim: [0]
  
  # Model checkpoint to evaluate
  synthetic_checkpoint: "results/models/advection_synthetic_model.pth"
  physical_checkpoint: "results/models/advection_physical_model.pth"
  
  # How many timesteps to rollout
  num_frames: 100
  
  # Output directory
  output_dir: "results/evaluation/advection"
  
  # Visualization settings
  visualization:
    format: "gif"  # or "mp4"
    fps: 10
    dpi: 100
      
