general:
  experiment_name: 'burgers_1d_experiment'
  mode: 'hybrid' # Options: 'physical', 'synthetic', 'hybrid'
  tasks: ['generate', 'train', 'evaluate']

data:
  data_dir: 'data/burgers_1d'
  dset_name: 'burgers_1d'
  num_simulations: 6
  trajectory_length: 100

model:
  physical:
    name: 'BurgersModel'
    model_path: 'results/models'
    model_save_name: 'burgers_physical_model_1d'
    domain:
      dimensions:
        x: {size: 100, resolution: 128}
    dt: 0.1
    pde_params:
      name: 'diffusion_field'
      type: 'field'
      value: '(x/size_x)**2'  # Spatially-varying diffusion field to learn
  synthetic:
    name: 'ResNet'
    model_path: 'results/models'
    model_save_name: 'burgers_synthetic_model_1d'
    architecture:
      layers: [128, 128]
      batch_norm: false

trainer:
  batch_size: 64
  rollout_steps: 5
  train_sim: [0]
  device: 'cuda:0'
  data_access: 'both'
  physical:
    epochs: 1
    rollout_steps: 1
    downsample_factor: 0
    method: 'L-BFGS-B'
    abs_tol: 1e-12
    max_iterations: 5
  synthetic:
    epochs: 100
    rollout_scheduler:
      start: 1
      end: 10
      strategy: 'exponential'
      exponent: 2.0
    learning_rate: 0.0001
    optimizer: 'adam'
    scheduler: 'cosine'
    weight_decay: 0.0
  hybrid:
    cycles: 50
    warmup: 5
    augmentation:
      alpha: 1.0
      cache_dir: data/cache_phiml

    # NEW: Loss scaling configuration
    loss_scaling:
      synthetic:
        real_weight: 1.0        # L coefficient
        interaction_weight: 1.0  # I coefficient
        proportional: false      # Auto-scale I to match L magnitude
      
      physical:
        real_weight: 1.0
        interaction_weight: 0.1  # Physical model sees weaker interaction loss
        proportional: true       # Or use proportional scaling


# For evaluation
evaluation:
  # Which simulations to evaluate
  test_sim: [0]

  # Model checkpoint to evaluate
  synthetic_checkpoint: "results/models/burgers_synthetic_model_1d.pth"
  physical_checkpoint: "results/models/burgers_physical_model_1d.npz"

  # How many timesteps to rollout
  num_frames: 100

  # Output directory
  output_dir: "results/evaluation/burgers_1d"

  # Visualization settings
  visualization:
    format: "gif"  # or "mp4"
    fps: 10
    dpi: 100

