# Burgers experiment configuration
defaults:
  - data: burgers_128
  - model/physical: burgers
  - model/synthetic: unet
  - trainer: synthetic
  - generation: default
  - evaluation: default
  - _self_

run_params:
  experiment_name: 'burgers_unet_128_v1'
  notes: 'Training UNet on Burgers 128x128'
  mode: [ 'evaluate']
  model_type: 'synthetic'

model:
  synthetic:
    model_save_name: 'burgers_unet_128'

generation_params:
  num_simulations: 10

trainer_params:
  train_sim: [0,1,2,3,4,5,6,7,8,9]  # 16 sims for training
  val_sim: [10]  # 4 sims for validation
  epochs: 100
  batch_size: 16
  num_predict_steps: 4
  use_sliding_window: true

evaluation_params:
  test_sim: [0]
  num_frames: 75

project_root: ${hydra:runtime.cwd}
