# Quick test for hybrid training - minimal configuration
defaults:
  - data: burgers_128
  - model/physical: burgers
  - model/synthetic: unet
  - trainer: hybrid
  - _self_

run_params:
  experiment_name: 'burgers_hybrid_quick_test'
  notes: 'Quick test of hybrid training implementation'
  mode: ['train']
  model_type: 'hybrid'

model:
  synthetic:
    model_save_name: 'burgers_hybrid_quick_test'

trainer_params:
  train_sim: [0, 1]
  val_sim: []
  epochs: 2
  num_predict_steps: 3
  alpha: 0.5
  warmup_epochs: 0
  interleave_frequency: 1
  
  synthetic:
    batch_size: 8
    learning_rate: 1e-4
    optimizer: adam
  
  physical:
    method: 'L-BFGS-B'
    abs_tol: 1e-6
    max_iterations: 3
    suppress_convergence_errors: true

project_root: ${hydra:runtime.cwd}
