# Quick test for Burgers inverse problem - 2 epochs only
defaults:
  - data: burgers_128
  - model/physical: burgers
  - trainer: physical_quick
  - generation: default
  - _self_

run_params:
  experiment_name: 'burgers_inverse_quick_test'
  notes: 'Quick inverse problem test with 2 epochs'
  mode: ['train']
  model_type: 'physical'

model:
  physical:
    model_path: 'results/models/'
    model_save_name: 'burgers_128'
    dt: 1.0

trainer_params:
  learning_rate: 0.0001
  epochs: 2
  num_predict_steps: 5
  train_sim: [0]
  learnable_parameters:
    - name: 'nu'
      initial_guess: 0.005

project_root: ${hydra:runtime.cwd}
