# Burgers Equation Experiment
# 
# This is a comprehensive configuration for the Burgers equation problem.
# Modify the settings below based on your needs:
#
# Quick Test Mode:
#   - Set epochs: 2, train_sim: [0,1], val_sim: [2]
#   - Set mode: ['train'] (skip evaluation for speed)
#
# Physical Model:
#   - Change model_type: 'physical'
#   - Use trainer: physical or physical_with_suppression
#   - Add learnable_parameters under trainer_params
#
# Hybrid Training:
#   - Change model_type: 'hybrid'
#   - Use trainer: hybrid
#
# Data Generation:
#   - Add 'generate' to mode: ['generate', 'train', 'evaluate']
#   - Set generation_params.num_simulations as needed

defaults:
  - data: burgers_128
  - model/physical: burgers
  - model/synthetic: unet
  - trainer: synthetic
  - generation: default
  - evaluation: default
  - _self_

run_params:
  experiment_name: 'burgers_experiment'
  notes: 'Burgers equation with synthetic UNet model'
  mode: ['train', 'evaluate']  # Options: generate, train, evaluate
  model_type: 'synthetic'  # Options: synthetic, physical, hybrid

model:
  synthetic:
    model_save_name: 'burgers_unet_128'

generation_params:
  num_simulations: 10
  total_steps: 100
  save_interval: 1

trainer_params:
  # Training data
  train_sim: [0,1,2,3,4,5,6,7,8]  # Training simulations
  val_sim: [9]  # Validation simulations
  
  # Training hyperparameters
  epochs: 100
  batch_size: 16
  num_predict_steps: 4
  
  # Optimizer (for synthetic/hybrid)
  learning_rate: 0.0001
  optimizer: 'adam'
  scheduler: 'cosine'
  weight_decay: 0.0
  
  # Validation
  validate_every: 1
  validation_rollout_steps: 75
  
  # Checkpointing
  checkpoint_freq: 10
  print_freq: 10

evaluation_params:
  test_sim: [0]
  num_frames: 75
  metrics: ['mse', 'mae', 'rmse']
  save_animations: true
  save_plots: true

project_root: ${hydra:runtime.cwd}
