general:
  experiment_name: 'burgers_2d_experiment'
  mode: 'hybrid' # Options: 'physical', 'synthetic', 'hybrid'
  tasks: ['generate', 'train', 'evaluate']

data:
  data_dir: 'data/burgers_2d'
  dset_name: 'burgers_2d'
  num_simulations: 6
  trajectory_length: 100

model:
  physical:
    name: 'BurgersModel'
    model_path: 'results/models'
    model_save_name: 'burgers_physical_model_2d'
    domain:
      dimensions:
        x: {size: 100, resolution: 64}
        y: {size: 100, resolution: 64}
    dt: 0.5
    pde_params:
      name: 'diffusion_field'
      type: 'field'
      value: '0.5 * ((x/size_x)**3 + (y/size_y)**3)'  # Spatially-varying diffusion field to learn
  synthetic:
    name: 'UNet'
    model_path: 'results/models'
    model_save_name: 'burgers_synthetic_model_2d'
    architecture:
      levels: 4
      filters: 64
      batch_norm: false

trainer:
  batch_size: 32
  rollout_steps: 5
  train_sim: [0]
  device: 'cuda:0'
  data_access: 'both'
  physical:
    epochs: 1
    rollout_steps: 1
    downsample_factor: 0
    method: 'L-BFGS-B'
    abs_tol: 1e-6
    max_iterations: 10
  synthetic:
    epochs: 10
    rollout_scheduler:
      start: 1
      end: 6
      strategy: 'exponential'
      exponent: 3.0
    learning_rate: 0.0001
    optimizer: 'adam'
    scheduler: 'cosine'
    weight_decay: 0.0
  hybrid:
    cycles: 10
    warmup: 1
    augmentation:
      alpha: 1.0
      cache_dir: data/cache_phiml


# For evaluation
evaluation:
  # Which simulations to evaluate
  test_sim: [0]

  # Model checkpoint to evaluate
  synthetic_checkpoint: "results/models/burgers_synthetic_model_2d.pth"
  physical_checkpoint: "results/models/burgers_physical_model_2d.npz"

  # How many timesteps to rollout
  num_frames: 100

  # Output directory
  output_dir: "results/evaluation/burgers_2d"

  # Visualization settings
  visualization:
    format: "gif"  # or "mp4"
    fps: 10
    dpi: 100

