# Burgers experiment configuration
defaults:
  - data: burgers_128
  - model/physical: burgers
  - model/synthetic: unet
  - trainer: synthetic
  - generation: default
  - evaluation: default
  - _self_

run_params:
  experiment_name: 'burgers_unet_128_v1'
  notes: 'Training UNet on Burgers 128x128'
  mode: ['train', 'evaluate']
  model_type: 'synthetic'

model:
  synthetic:
    model_save_name: 'burgers_unet_128'

trainer_params:
  train_sim: [0, 1, 2, 3, 4, 5, 6, 7, 8]
  epochs: 100
  batch_size: 32

evaluation_params:
  test_sim: [0, 9]
  num_frames: 51

project_root: ${hydra:runtime.cwd}
