# Heat inverse problem experiment
defaults:
  - data: heat_64
  - model/physical: heat
  - trainer: physical
  - generation: default
  - _self_

run_params:
  experiment_name: 'heat_inverse_problem_v1'
  notes: 'Training physical model to find optimal diffusivity'
  mode: ['train']
  model_type: 'physical'

model:
  physical:
    model_path: 'results/models/'
    model_save_name: 'heat_64'

generation_params:
  total_steps: 20

trainer_params:
  learning_rate: 0.000000000001  # 1e-12
  epochs: 50
  num_predict_steps: 4
  train_sim: [0]
  learnable_parameters:
    - name: 'diffusivity'
      initial_guess: 2.0

project_root: ${hydra:runtime.cwd}
