general:
  experiment_name: 'inviscid_burgers_1d_experiment'
  mode: 'hybrid' # Options: 'physical', 'synthetic', 'hybrid'
  tasks: [ 'train', 'evaluate']

data:
  data_dir: 'data/inviscid_burgers_1d'
  dset_name: 'inviscid_burgers_1d'
  num_simulations: 6
  trajectory_length: 50

model:
  physical:
    name: 'InviscidBurgersModel'
    model_path: 'results/models'
    model_save_name: 'inviscid_burgers_physical_model_1d'
    domain:
      dimensions:
        x: {size: 100, resolution: 256}
    dt: 0.2
    pde_params:
      name: 'potential_field'
      type: 'field'
      value: ' math.sin(2 * math.pi * x / size_x)'  # Spatially-varying potential field to learn (forcing = -∇φ)
  synthetic:
    name: 'ResNet'
    model_path: 'results/models'
    model_save_name: 'inviscid_burgers_synthetic_model_1d'
    architecture:
      levels: 3
      filters: 32
      batch_norm: false

trainer:
  batch_size: 128
  rollout_steps: 6
  train_sim: [0]
  device: 'cuda:0'
  data_access: 'both'
  physical:
    epochs: 1
    rollout_steps: 1
    downsample_factor: 2
    method: 'L-BFGS-B'
    abs_tol: 1e-12
    max_iterations: 10
    regularization:
      type: 'l2_gradient'  # or 'tv', 'laplacian'
      weight: 1e-3  # May need less regularization than diffusion
      difference: 'forward'
  synthetic:
    epochs: 100
    rollout_scheduler:
      start: 1
      end: 6
      strategy: 'exponential'
      exponent: 2.0
    learning_rate: 0.0001
    optimizer: 'adam'
    scheduler: 'cosine'
    weight_decay: 0.0
  hybrid:
    cycles: 10
    warmup: 2
    augmentation:
      alpha: 1.0
      num_trajectories: 2
       # NEW: Variable trajectory length options
      full_trajectory_length: 100    # Full physical trajectory for synthetic training
      synthetic_trajectory_length: 10  # Short synthetic trajectory for physical training
      num_start_points: 10           # Starting points sampled per physical trajectory
      start_point_sampling: 'uniform'  # 'uniform' or 'random'
      cache_dir: data/cache_phiml

    # Loss scaling configuration
    loss_scaling:
      synthetic:
        real_weight: 1.0        # L coefficient
        interaction_weight: 1.0  # I coefficient
        proportional: false      # Auto-scale I to match L magnitude

      physical:
        real_weight: 1.0
        interaction_weight: 0.1  # Physical model sees weaker interaction loss
        proportional: true      # Or use proportional scaling

sparsity:
  temporal:
    enabled: false
    mode: endpoints
    start_fraction: 0.1
    end_fraction: 0.1
    uniform_stride: 1
    custom_fractions: []

  spatial:
    enabled: true
    mode: center
    center_fraction: 0.5
# For evaluation
evaluation:
  # Which simulations to evaluate
  test_sim: [0, 1]

  # Model checkpoint to evaluate
  synthetic_checkpoint: "results/models/inviscid_burgers_synthetic_model_1d.pth"
  physical_checkpoint: "results/models/inviscid_burgers_physical_model_1d.npz"

  # How many timesteps to rollout
  num_frames: 100

  # Output directory
  output_dir: "results/evaluation/inviscid_burgers_1d"

  # Visualization settings
  visualization:
    format: "gif"  # or "mp4"
    fps: 10
    dpi: 100
