general:
  experiment_name: 'inviscid_burgers_2d_experiment'
  mode: 'hybrid' # Options: 'physical', 'synthetic', 'hybrid'
  tasks: ['generate', 'train', 'evaluate']

data:
  data_dir: 'data/inviscid_burgers_2d'
  dset_name: 'inviscid_burgers_2d'
  num_simulations: 6
  trajectory_length: 100

model:
  physical:
    name: 'InviscidBurgersModel'
    model_path: 'results/models'
    model_save_name: 'inviscid_burgers_physical_model_2d'
    domain:
      dimensions:
        x: {size: 100, resolution: 256}
        y: {size: 100, resolution: 256}
    dt: 0.2
    pde_params:
      name: 'potential_field'
      type: 'field'
      value: 'math.sin(2 * math.pi * x / size_x) * math.sin(2 * math.pi * y / size_y)'  # Spatially-varying potential field to learn (forcing = -∇φ)
  synthetic:
    name: 'UNet'
    model_path: 'results/models'
    model_save_name: 'inviscid_burgers_synthetic_model_2d'
    architecture:
      levels: 4
      filters: 64
      batch_norm: false

trainer:
  batch_size: 128
  rollout_steps: 6
  train_sim: [0]
  device: 'cuda:0'
  data_access: 'both'
  physical:
    epochs_per_cycle: 1  # Base value used in hybrid training
    epochs: ${trainer.physical.epochs_per_cycle}  # Default: same as per-cycle
    standalone_epochs: ${multiply:${trainer.physical.epochs_per_cycle},${trainer.hybrid.cycles}}
    rollout_steps: 1
    downsample_factor: 2
    method: 'L-BFGS-B'
    abs_tol: 1e-12
    max_iterations: 10
    regularization:
      type: 'l2_gradient'  # or 'tv', 'laplacian'
      weight: 1e-3  # May need less regularization than diffusion
      difference: 'forward'
  synthetic:
    epochs_per_cycle: 100  # Base value used in hybrid training
    epochs: ${trainer.synthetic.epochs_per_cycle}  # Default: same as per-cycle
    standalone_epochs: ${total_synthetic_epochs:${trainer.synthetic.epochs_per_cycle},${trainer.hybrid.cycles},${trainer.hybrid.warmup}}
    rollout_scheduler:
      start: 1
      end: 4
      strategy: 'exponential'
      exponent: 2.0
    learning_rate: 0.0001
    optimizer: 'adam'
    scheduler: 'cosine'
    weight_decay: 0.0
  hybrid:
    cycles: 1
    warmup: 1
    augmentation:
      alpha: 1.0
      num_trajectories: 5
       # NEW: Variable trajectory length options
      physical_trajectory_length: 100    # Full physical trajectory for synthetic training
      synthetic_trajectory_length: 10  # Short synthetic trajectory for physical training
      cache_dir: data/cache_phiml

    # Loss scaling configuration
    loss_scaling:
      synthetic:
        real_weight: 1.0        # L coefficient
        interaction_weight: 1.0  # I coefficient
        proportional: false      # Auto-scale I to match L magnitude

      physical:
        real_weight: 1.0
        interaction_weight: 0.1  # Physical model sees weaker interaction loss
        proportional: true      # Or use proportional scaling

sparsity:
  temporal:
    enabled: false
    mode: endpoints
    start_fraction: 0.1
    end_fraction: 0.1
    uniform_stride: 1
    custom_fractions: []

  spatial:
    enabled: true
    mode: center
    center_fraction: 0.5
# For evaluation
evaluation:
  # Which simulations to evaluate
  test_sim: [0,1,2,3,4,5]

  # Primary synthetic model checkpoint (e.g., trained on real data only)
  synthetic_checkpoint: "results/models/inviscid_burgers_synthetic_model_2d.pth"
  
  # Hybrid synthetic model checkpoint (optional, from HYCO training)
  synthetic_checkpoint_hybrid: "results/models/inviscid_burgers_hybrid_synthetic_2d.pth"

  # Primary physical model checkpoint (e.g., trained on real data only)  
  physical_checkpoint: "results/models/inviscid_burgers_physical_model_2d.npz"
  
  # Hybrid physical model checkpoint (optional, from HYCO training)
  physical_checkpoint_hybrid: "results/models/inviscid_burgers_hybrid_physical_2d.npz"

  # How many timesteps to rollout
  num_frames: 100

  # Output directory
  output_dir: "results/evaluation/inviscid_burgers_2d"

  # Visualization settings
  visualization:
    format: "gif"
    fps: 10
    dpi: 100
