general: 
  experiment_name: 'kolmogorov_experiment'
  mode: 'hybrid' # Options: 'physical', 'synthetic', 'hybrid'
  tasks: ['generate', 'evaluate']

data:
  data_dir: 'data/kolmogorov'
  dset_name: 'kolmogorov'
  num_simulations: 1
  trajectory_length: 300

model:
  physical:
    name: 'KolmogorovModel'
    model_path: 'results/models'
    model_save_name: 'kolmogorov_physical_model'
    domain: 
      size_x: 100
      size_y: 100
    resolution:
      x: 256
      y: 256
    dt: 0.05
    pde_params:
      nu: 0.0001  # Kinematic viscosity
      name: 'forcing_field'
      type: 'field'
      value: "[math.sin(4*math.pi*y/size_y), 0*x]"  # Sinusoidal forcing in y-direction
  synthetic:
    name: 'UNet'
    model_path: 'results/models'
    model_save_name: 'kolmogorov_synthetic_model' 
    architecture: 
      levels: 4
      filters: 64

trainer:
  batch_size: 8
  rollout_steps: 4 
  train_sim: [0]
  device: 'cuda:0'
  data_access: 'both'
  physical: 
    epochs: 1 
    learnable_parameters:
      - name: 'forcing_field'
        type: 'field'
        initial_guess: 'math.stack([math.sin(4*math.pi*y/size_y), 0*x], channel("vector"))'
    method: 'L-BFGS-B'
    abs_tol: 1e-4
    max_iterations: 5
  synthetic:
    epochs: 2
    learning_rate: 0.0001
    optimizer: 'adam'
    scheduler: 'cosine'
    weight_decay: 0.0
  hybrid:
    cycles: 2
    warmup: 1
    augmentation:
      alpha: 0.2
      cache_dir: data/cache_phiml  # PhiML cache uses .npz format


# For evaluation
evaluation:
  # Which simulations to evaluate
  test_sim: [0]
  
  # Model checkpoint to evaluate
  physical_checkpoint: "results/models/kolmogorov_physical_model.pth"
  synthetic_checkpoint: "results/models/kolmogorov_synthetic_model.pth"
  
  # How many timesteps to rollout
  num_frames: 300
  
  # Output directory
  output_dir: "results/evaluation/kolmogorov"
  
  # Visualization settings
  visualization:
    format: "gif"  # or "mp4"
    fps: 10
    dpi: 100
