general:
  experiment_name: 'navier_stokes_2d_experiment'
  mode: 'hybrid'
  tasks: [ 'train','evaluate']

data:
  data_dir: 'data/navier_stokes_2d'
  dset_name: 'navier_stokes_2d'
  num_simulations: 6
  trajectory_length: 100

model:
  physical:
    name: 'NavierStokesModel'
    model_path: 'results/models'
    model_save_name: 'navier_stokes_physical_model_2d'
    domain:
      dimensions:
        x: {size: 100, resolution: 128}
        y: {size: 100, resolution: 128}
    dt: 0.1
    pde_params:
      name: 'buoyancy_field'
      type: 'field'  # 'scalar' or 'field'
      value: '1.0 + 0.4 * math.sin(2 * math.pi * x / size_x)'
  synthetic:
    name: 'UNet'
    model_path: 'results/models'
    model_save_name: 'navier_stokes_synthetic_model_2d'
    architecture:
      levels: 4
      filters: 128
      batch_norm: false
    input_noise:
      enabled: true
      scale: 0.01  # Standard deviation of Gaussian noise
      type: 'gaussian'  # Currently only 'gaussian' is supported


trainer:
  batch_size: 64
  rollout_steps: 8
  train_sim: [0]
  device: 'cuda:0'
  data_access: 'both'
  physical:
    epochs_per_cycle: 1
    epochs: ${trainer.physical.epochs_per_cycle}
    standalone_epochs: ${multiply:${trainer.physical.epochs_per_cycle},${trainer.hybrid.cycles}}
    rollout_steps: 1
    downsample_factor: 1
    method: 'L-BFGS-B'
    abs_tol: 1e-12
    max_iterations: 20
    regularization:
      type: 'l2_gradient'
      weight: 1e-2
      difference: 'forward'
  synthetic:
    epochs_per_cycle: 200
    epochs: ${trainer.synthetic.epochs_per_cycle}
    standalone_epochs: ${total_synthetic_epochs:${trainer.synthetic.epochs_per_cycle},${trainer.hybrid.cycles},${trainer.hybrid.warmup}}
    rollout_scheduler:
      start: 1
      end: 8
      strategy: 'exponential'
      exponent: 1.5
    learning_rate: 0.0001
    optimizer: 'adam'
    scheduler: 'cosine'
    weight_decay: 0.0
  hybrid:
    cycles: 80
    warmup: 20
    augmentation:
      alpha: 1.0
      num_trajectories: 5
      physical_trajectory_length: 100
      synthetic_trajectory_length: 10
      cache_dir: data/cache_phiml

    loss_scaling:
      synthetic:
        real_weight: 1.0
        interaction_weight: 1.0
        proportional: false

      physical:
        real_weight: 1.0
        interaction_weight: 0.1
        proportional: true

    # Loss-based model reversion: only keep trained models if loss improved
    reversion:
      enabled: false  # Set to true to enable
      synthetic: true  # Revert synthetic model if its loss increased
      physical: true   # Revert physical model if its loss increased

sparsity:
  temporal:
    enabled: false
    mode: endpoints
    start_fraction: 0.1
    end_fraction: 0.1
    uniform_stride: 1
    custom_fractions: []

  spatial:
    enabled: true
    mode: center
    center_fraction: 0.8

evaluation:
  test_sim: [0,1,2,3,4,5]

  synthetic_checkpoint: "results/models/navier_stokes_synthetic_model_2d.pth"
  synthetic_checkpoint_hybrid: "results/models/navier_stokes_hybrid_synthetic_2d.pth"
  
  physical_checkpoint: "results/models/navier_stokes_physical_model_2d.npz"
  physical_checkpoint_hybrid: "results/models/navier_stokes_hybrid_physical_2d.npz"

  num_frames: 100
  output_dir: "results/evaluation/navier_stokes_2d"

  visualization:
    format: "gif"
    fps: 10
    dpi: 100