general:
  experiment_name: 'smoke_plume_2d_experiment'
  mode: 'hybrid'
  tasks: ['evaluate']

data:
  data_dir: 'data/smoke_plume_2d'
  dset_name: 'smoke_plume_2d'
  num_simulations: 5
  trajectory_length: 100

model:
  physical:
    name: 'SmokePlumeModel'
    model_path: 'results/models'
    model_save_name: 'smoke_plume_physical_model_2d'
    domain:
      dimensions:
        x: {size: 100, resolution: 64}
        y: {size: 100, resolution: 64}
    dt: 0.1
    pde_params:
      name: 'buoyancy_field'
      type: 'field'  # 'scalar' or 'field'
      value: '1.0 + 0.4 * math.sin(2 * math.pi * x / size_x)'
  synthetic:
    name: 'UNet'
    model_path: 'results/models'
    model_save_name: 'smoke_plume_synthetic_model_2d'
    architecture:
      levels: 4
      filters: 64
      batch_norm: false

trainer:
  batch_size: 32
  rollout_steps: 4
  train_sim: [0]
  device: 'cuda:0'
  data_access: 'both'
  physical:
    epochs_per_cycle: 1
    epochs: ${trainer.physical.epochs_per_cycle}
    standalone_epochs: ${multiply:${trainer.physical.epochs_per_cycle},${trainer.hybrid.cycles}}
    rollout_steps: 1
    downsample_factor: 0
    method: 'L-BFGS-B'
    abs_tol: 1e-10
    max_iterations: 15
    regularization:
      type: 'l2_gradient'
      weight: 1e-4
  synthetic:
    epochs_per_cycle: 10
    epochs: ${trainer.synthetic.epochs_per_cycle}
    standalone_epochs: ${total_synthetic_epochs:${trainer.synthetic.epochs_per_cycle},${trainer.hybrid.cycles},${trainer.hybrid.warmup}}
    rollout_scheduler:
      start: 1
      end: 4
      strategy: 'exponential'
      exponent: 2.0
    learning_rate: 0.0001
    optimizer: 'adam'
    scheduler: 'cosine'
    weight_decay: 0.0
  hybrid:
    cycles: 10
    warmup: 2
    augmentation:
      alpha: 1.0
      num_trajectories: 5
      physical_trajectory_length: 100
      synthetic_trajectory_length: 20
      cache_dir: data/cache_phiml

    loss_scaling:
      synthetic:
        real_weight: 1.0
        interaction_weight: 1.0
        proportional: false

      physical:
        real_weight: 1.0
        interaction_weight: 0.01
        proportional: false

sparsity:
  temporal:
    enabled: false
    mode: endpoints
    start_fraction: 0.1
    end_fraction: 0.1
    uniform_stride: 1
    custom_fractions: []

  spatial:
    enabled: false
    mode: center
    center_fraction: 0.6

evaluation:
  test_sim: [0, 1]

  synthetic_checkpoint: "results/models/smoke_plume_synthetic_model_2d.pth"
  synthetic_checkpoint_hybrid: "results/models/smoke_plume_hybrid_synthetic_2d.pth"
  
  physical_checkpoint: "results/models/smoke_plume_physical_model_2d.npz"
  physical_checkpoint_hybrid: "results/models/smoke_plume_hybrid_physical_2d.npz"

  num_frames: 100
  output_dir: "results/evaluation/smoke_plume_2d"

  visualization:
    format: "gif"
    fps: 10
    dpi: 100