# Smoke experiment configuration
defaults:
  - data: smoke_128
  - model/physical: smoke
  - model/synthetic: smoke_unet
  - trainer: synthetic
  - generation: default
  - evaluation: default
  - _self_

run_params:
  experiment_name: 'smoke_unet_128_v1'
  notes: 'Training UNet on Smoke 128x128'
  mode: ['evaluate']
  model_type: 'synthetic'

model:
  synthetic:
    model_save_name: 'smoke_unet_128'

trainer_params:
  train_sim: [0, 1]
  epochs: 100
  batch_size: 16
  num_predict_steps: 4
  use_sliding_window: true

evaluation_params:
  test_sim: [0, 1]
  num_frames: 75

project_root: ${hydra:runtime.cwd}
