# configs/burgers.yaml

model_name: "BurgersModel"

domain:
  size_x: 100
  size_y: 100
resolution:
  x: 128
  y: 128

dt: 0.5

# --- UPDATED: Added batch_size and inflow_rate ---
pde_params:
  batch_size: 1
  nu: 0.0

data_generation:
  num_simulations: 1
  total_steps: 50
  save_interval: 1

output_data:
  output_dir: "data/"
  dataset_name: "burgers_v1"
  fields_to_save: ["velocity"]
  fields_scheme: "VV"