# configs/heat_inverse_experiment.yaml
#
# Config to run the PhysicalTrainer for the inverse heat problem.
# This finds the 'diffusivity' parameter from data.

run_params:
  experiment_name: "burgers_inverse_problem_v1"
  notes: "Training a physical model (BurgersModel) to find the optimal viscosity."
  mode: ['generate_scene']
  model_type: 'physical'

# --- Data Configuration ---
data:
  data_dir: 'data/'
  dset_name: 'burgers_128' 
  fields: ['velocity']
  fields_scheme: 'VV'

# --- Data Generation Parameters ---
generation_params:
  # These parameters describe the data in 'dset_name'
  model_name: 'BurgersModel'
  num_simulations: 1
  total_steps: 50       # Total steps in the saved simulation data
  save_interval: 1

# --- Model Definitions (Plug-and-Play) ---
model:
  physical:
    name: 'BurgersModel' # Class name in src.models.physical
    model_path: 'results/models/'
    model_save_name: 'burgers_128'
      
    # Model parameters
    domain: { size_x: 100, size_y: 100 }
    resolution: { x: 128, y: 128 }
    dt: 1.0
    pde_params:
      batch_size: 1
      nu: 0.1 # Ground truth value used for data generation



trainer_params:
  learning_rate: 1.0e-4  # Learning rate from inverse_heat.py
  batch_size: 16         # Number of samples per gradient update, not yet implemented in PhysicalTrainer
  epochs: 50             # Number of passes over the dataset
  num_predict_steps: 5   
  
  train_sim: [0] # Which simulations to use for training
  learnable_parameters:
    - name: 'nu'  # Must match the attribute name in the PhysicalModel
      initial_guess: 0.005