# configs/burgers.yaml

model_name: "BurgersModel"

domain:
  size_x: 100
  size_y: 100
resolution:
  x: 512
  y: 512

dt: 0.2

# --- UPDATED: Added batch_size and inflow_rate ---
pde_params:
  batch_size: 1
  nu: 0.0

data_generation:
  num_simulations: 100
  total_steps: 200
  save_interval: 1

output_data:
  output_dir: "data/"
  dataset_name: "burgers_512"
  fields_to_save: ["Velocity"]
  fields_scheme: "VV"