# configs/smoke.yaml

model_name: "SmokeModel"

domain:
  size_x: 80
  size_y: 100
resolution:
  x: 64
  y: 80

dt: 1.0

# --- UPDATED: Added batch_size and inflow_rate ---
pde_params:
  batch_size: 1
  nu: 0.0
  buoyancy: 1.0
  inflow_radius: 10.0
  inflow_rate: 0.1 
  # Store the randomization ranges from the original script
  inflow_rand_x_range: [0.2, 0.6]  # (min_factor, mult_factor)
  inflow_rand_y_range: [0.1, 0.2]  # (min_factor, mult_factor)

data_generation:
  num_simulations: 10
  total_steps: 50
  save_interval: 1

output_data:
  output_dir: "data/"
  dataset_name: "smoke_v1"
  fields_to_save: ["density", "velocity", "inflow"]
  fields_scheme: "dVVc"