# --- Run Parameters Block ---
run_params:
  experiment_name: "smoke_unet_128_v1"
  notes: "Training a synthetic UNet model on Smoke 128x128 data."
  mode: ['evaluate']          # Replaces the top-level 'task' field
  model_type: 'synthetic'  # Tells run.py to use SyntheticTrainer

# --- Data Configuration (for all tasks) ---
data:
  data_dir: 'data/'
  dset_name: 'smoke_128'
  fields: ['density', 'velocity', 'inflow']
  fields_scheme: 'dVVi'

# --- Model Definitions (Plug-and-Play) ---
model:
  # Physical model used for data generation
  physical:
    name: 'SmokeModel' # Class name in src.models.physical
    domain: { size_x: 100, size_y: 100 }
    resolution: { x: 128, y: 128 }
    dt: 0.8
    pde_params:
      nu: 0.0
      buoyancy: 1.0
      inflow_radius: 10.0
      inflow_rate: 0.1 
      inflow_rand_x_range: [0.2, 0.6]
      inflow_rand_y_range: [0.15, 0.05]
      
  # Synthetic model used for training/evaluation
  synthetic:
    name: 'UNet' # Class name in src.models.synthetic
    model_path: 'results/models'
    model_save_name: 'smoke_unet_128'
    # The model's internal structure is defined by its specs
    input_specs:
      density: 1
      velocity: 2
      inflow: 1
    output_specs:
      density: 1
      velocity: 2
    # Hyperparameters for the UNet class itself
    architecture:
      levels: 4
      filters: 64
      batch_norm: true

# --- Task-Specific Parameters ---
# Parameters for the 'generate' task
generation_params:
  num_simulations: 10
  total_steps: 50
  save_interval: 1

# Parameters for the 'train' task
trainer_params:
  learning_rate: 1.0e-4
  batch_size: 16
  epochs: 1000
  num_predict_steps: 3 # Autoregressive rollout length
  train_sim: [0,1,2,3,4,5,6,7,8] # Simulations to use for training
  use_sliding_window: true # If true, creates multiple samples per simulation using sliding windows

# Parameters for the 'evaluate' task
evaluation_params:
  test_sim: [0,9]           # Simulations to evaluate
  num_frames: 51                # Number of timesteps to rollout
  metrics: ['mse', 'mae', 'rmse']  # Metrics to compute
  keyframe_count: 5             # Number of keyframes in comparison plot
  animation_fps: 10             # Frame rate for GIF animations
  save_animations: true         # Generate comparison animations
  save_plots: true              # Generate error plots and keyframe comparisons
