# --- Task Definition ---
task: 'train' # Can be 'generate', 'train', 'evaluate', 'subsample'
project_root: '.' # Relative path to project root

# --- Data Configuration (for all tasks) ---
data:
  data_dir: 'data/'
  dset_name: 'smoke_128'
  fields: ['density', 'velocity', 'inflow']
  fields_scheme: 'dVVi

# --- Model Definitions (Plug-and-Play) ---
model:
  # Physical model used for data generation
  physical:
    name: 'SmokeModel' # Class name in src.models.physical
    domain: { size_x: 100, size_y: 100 }
    resolution: { x: 128, y: 128 }
    dt: 0.8
    pde_params:
      nu: 0.0
      buoyancy: 1.0
      inflow_radius: 10.0
      inflow_rate: 0.1 
      inflow_rand_x_range: [0.2, 0.6]
      inflow_rand_y_range: [0.15, 0.05]
      
  # Synthetic model used for training/evaluation
  synthetic:
    name: 'UNet' # Class name in src.models.synthetic
    model_path: 'results/models'
    model_save_name: 'smoke_unet_128'
    # The model's internal structure is defined by its specs
    input_specs:
      density: 1
      velocity: 2
      inflow: 1
    output_specs:
      density: 1
      velocity: 2
    # Hyperparameters for the UNet class itself
    architecture:
      levels: 4
      filters: 64
      batch_norm: true

# --- Task-Specific Parameters ---
# Parameters for the 'generate' task
generation_params:
  num_simulations: 25
  total_steps: 50
  save_interval: 1

# Parameters for the 'train' task
trainer_params:
  learning_rate: 1.0e-4
  batch_size: 16
  epochs: 50
  num_predict_steps: 4 # Autoregressive rollout length
  train_sim: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15] # Simulations to use for training
  test_sim: [16] # Simulations to use for testing