# configs/smoke.yaml

model_name: "SmokeModel"

domain:
  size_x: 100
  size_y: 100
resolution:
<<<<<<< HEAD
  x: 256
  y: 256
=======
  x: 128
  y: 160
>>>>>>> 3a81eeb2ed50798d643659d7b56a5015a3a0b60b

dt: 0.5

# --- UPDATED: Added batch_size and inflow_rate ---
pde_params:
  batch_size: 1
  nu: 0.0
  buoyancy: 1.0
  inflow_radius: 10.0
  inflow_rate: 0.1 
  inflow_rand_x_range: [0.2, 0.8]
<<<<<<< HEAD
  inflow_rand_y_range: [0.1, 0.15]
=======
  inflow_rand_y_range: [0.15, 0.25]
>>>>>>> 3a81eeb2ed50798d643659d7b56a5015a3a0b60b

data_generation:
  num_simulations: 10
  total_steps: 100
  save_interval: 1

output_data:
  output_dir: "data/"
  dataset_name: "smoke_v1"
  fields_to_save: ["density", "velocity", "inflow"]
  fields_scheme: "dVVc"