# Hydra runtime configuration
# Disables Hydra's duplicate logging to keep output clean

run:
  dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}

job_logging:
  version: 1
  formatters:
    simple:
      format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      formatter: simple
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
  root:
    level: INFO
    handlers: [console, file]
  disable_existing_loggers: false

hydra_logging:
  version: 1
  formatters:
    simple:
      format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      stream: ext://sys.stdout
  root:
    level: WARNING  # Only show warnings from Hydra itself
    handlers: [console]
  disable_existing_loggers: false
