# @package _global_.trainer_params
# Quick check/test trainer for physical models
# Note: 'epochs' parameter controls max optimization iterations per simulation
batch_size: 1
epochs: 20  # Max iterations per simulation for quick testing
num_predict_steps: 5

train_sim: []

# Learnable parameters for inverse problems
learnable_parameters: []

# Optimizer settings
method: 'L-BFGS-B'
abs_tol: 0.000001
