# @package _global_.trainer_params
# Note: 'epochs' parameter controls max optimization iterations per simulation
batch_size: 1
epochs: 50  # Max iterations per simulation
num_predict_steps: 5

train_sim: []

# Learnable parameters for inverse problems
learnable_parameters: []

# Optimizer settings
method: 'L-BFGS-B'
abs_tol: 1e-6

# Progress reporting
print_freq: 10

# Checkpoint settings
checkpoint_freq: 10
