# @package _global_.trainer_params
# Quick check/test trainer for physical models - only 2 epochs
learning_rate: 0.0001
batch_size: 1
epochs: 2
num_predict_steps: 5

train_sim: []

# Learnable parameters for inverse problems
learnable_parameters: []

# Optimizer settings
method: 'L-BFGS-B'
abs_tol: 0.000001
max_iterations: null
