# @package _global_.trainer_params
# Quick check/test trainer - only 2 epochs for fast validation
learning_rate: 0.0001
batch_size: 16
epochs: 2
num_predict_steps: 4

train_sim: []
val_sim: []

use_sliding_window: false

# Validation settings
validate_every: 1
validate_on_train: false

# Early stopping (disabled for quick tests)
early_stopping:
  enabled: false
  patience: 10
  min_delta: 1e-6
  monitor: val_loss

# Optimizer settings
optimizer: 'adam'
scheduler: 'cosine'
weight_decay: 0.0

# Checkpoint settings
save_interval: 1
save_best_only: false
checkpoint_freq: 50

# Progress reporting
print_freq: 10

# Memory monitoring
memory_monitor_batches: 5
