# @package _global_.trainer_params
learning_rate: 0.0001
batch_size: 16
epochs: 100
num_predict_steps: 4

train_sim: []
val_sim: null

use_sliding_window: true

# Optimizer settings
optimizer: 'adam'
scheduler: 'cosine'
weight_decay: 0.0

# Checkpoint settings
save_interval: 10
save_best_only: true
