# @package _global_.trainer_params
# Quick check/test trainer - only 2 epochs for fast validation
# Note: Hardcoded behaviors same as synthetic.yaml

learning_rate: 0.0001
batch_size: 16
epochs: 2
num_predict_steps: 4

train_sim: []
val_sim: []

# Validation settings
validate_every: 1
validation_rollout_steps: 10  # Short rollout for quick testing

# Optimizer settings
optimizer: 'adam'
scheduler: 'cosine'
weight_decay: 0.0

# Checkpoint settings
checkpoint_freq: 1

# Progress reporting
print_freq: 10
