# @package _global_.trainer_params
# Quick test with memory monitoring enabled
learning_rate: 0.0001
batch_size: 16
epochs: 2
num_predict_steps: 4

train_sim: []
val_sim: null

use_sliding_window: false

# Memory monitoring settings
enable_memory_monitoring: true  # Enable memory tracking
memory_monitor_batches: 5       # Print detailed info for first 5 batches

# Optimizer settings
optimizer: 'adam'
scheduler: 'cosine'
weight_decay: 0.0

# Checkpoint settings
save_interval: 1
save_best_only: false
