"""
PhiFlow Simulation: Compressible Isothermal Euler Equations
Natural Gas pipe with Hydrogen injection.

Key Physics:
- Compressible: Density varies.
- Equation of State: Pressure depends on species density.
- H2 is 'stiffer': High gas constant creates high pressure, causing expansion.
"""

from phi.torch.flow import *
from tqdm import trange
import matplotlib.pyplot as plt

# ============================================================
# 1. CONFIGURATION
# ============================================================

# Domain
ARENA_SIZE = Box(x=200, y=40)
RES = (200, 40)

# Simulation parameters
DT = 0.01  # Smaller DT needed for compressible flow (CFL condition)
STEPS = 2000

# Gas Properties (Isothermal Speed of Sound squared)
# H2 is much "springier" than Methane.
# Real physics: c_H2 ~ 1300 m/s, c_CH4 ~ 450 m/s.
# We scale these down for numerical stability while keeping ratio ~3:1
C_SQUARED_NG = 4.0   # Methane stiffness
C_SQUARED_H2 = 36.0  # Hydrogen stiffness (creates strong expansion)
# Assuming you have defined this constant outside the function
D_H2_NG = 1  # Example value in m^2/s (Check literature for accurate value)

# Physics
GRAVITY = math.tensor((0, 0.2), channel(vector="x,y")) # Gravity points down
DAMPING = 0.00001 # Artificial viscosity to prevent shockwave ringing

# Injection
INJECT_POS = math.tensor((30, 20), channel(vector="x,y"))
INJECT_RADIUS = 5
INJECT_RATE = 0.05

print("="*60)
print("   COMPRESSIBLE EULER SIMULATION")
print("="*60)

# Function for Poiseuille profile
def inlet_profile(location):
    y = location[1]
    y_norm = (y - RES[1]/2) / (RES[1]/2)  # Normalize y to [-1, 1]
    return vec(x=10.0 * (1 - y_norm**2), y=0)

# --- 1. The Target Velocity Field ---
# This grid contains the perfect flow profile everywhere.
target_velocity = CenteredGrid(
    inlet_profile,  # Initialize with zeros
    extrapolation=extrapolation.combine_sides(
        x=(extrapolation.BOUNDARY, extrapolation.BOUNDARY), # Left/Right Open
        y=(extrapolation.ZERO,     extrapolation.ZERO)      # Top/Bottom STICKY
    ),
    x=RES[0], y=RES[1], bounds=ARENA_SIZE
)

# --- 2. The Inflow Mask (Width = 1) ---
# A box from x=0 to x=1, spanning full height (y=0 to y=40)
inflow_zone = Box(x=(0, 1), y=(0, 40))

inflow_mask = CenteredGrid(
    values=inflow_zone,
    extrapolation=extrapolation.ZERO,
    x=RES[0], y=RES[1], bounds=ARENA_SIZE
)

# --- 3. Simulation Grids ---
velocity = target_velocity  # Start with full flow

rho_ng = CenteredGrid(1.5, extrapolation=extrapolation.BOUNDARY, x=RES[0], y=RES[1], bounds=ARENA_SIZE)
rho_h2 = CenteredGrid(0.0, extrapolation=extrapolation.BOUNDARY, x=RES[0], y=RES[1], bounds=ARENA_SIZE)

# Hydrogen Injector (Downstream)
injector = Sphere(center=INJECT_POS, radius=INJECT_RADIUS)
injector = CenteredGrid(
    values=injector,
    extrapolation=extrapolation.ZERO,
    x=RES[0], y=RES[1], bounds=ARENA_SIZE
)


# ============================================================
# 3. PHYSICS STEP (EULER SOLVER)
# ============================================================

@math.jit_compile
def euler_step(v, r_ng, r_h2, dt=DT):
    
   
    # In Euler, mass and velocity transport themselves
    r_ng_advected = advect.mac_cormack(r_ng, v, dt)
    r_h2_advected = advect.mac_cormack(r_h2, v, dt)
    v_advected    = advect.mac_cormack(v, v, dt)

    # --- 2. Injection (Source Term) ---
    # We add Mass to the H2 field. 
    # Note: We do NOT manually set velocity here.
    # The pressure generated by this added mass will PUSH the velocity automatically.
    h2_source = injector * INJECT_RATE * dt
    r_h2_new = r_h2_advected + h2_source
    r_ng_new = r_ng_advected - h2_source
    
    # --- 3. Compute Pressure (Equation of State) ---
    # P = rho * c^2
    # Total Pressure is sum of partial pressures
    pressure = (r_ng_new * C_SQUARED_NG) + (r_h2_new * C_SQUARED_H2)

    # Apply diffusion to H2
    r_h2_new = diffuse.explicit(r_h2_new, 
                                     diffusivity=D_H2_NG, 
                                     dt=dt)
    
    # Apply diffusion to NG
    r_ng_new = diffuse.explicit(r_ng_new, 
                                     diffusivity=D_H2_NG, 
                                     dt=dt)
    
    # --- 4. Apply Forces (Momentum Equation) ---
    
    # A. Pressure Gradient Force: F = -grad(P)
    # We need acceleration a = F / m  => a = -grad(P) / rho_total
    rho_total = r_ng_new + r_h2_new + 1e-4
    
    # Calculate gradient on staggered grid (aligned with velocity components)
    # type=type(v) ensures the gradient returns a StaggeredGrid
    grad_p = field.spatial_gradient(pressure)
    
    # Interpolate density to velocity sample points to divide
    pressure_accel = -grad_p / rho_total
    
    # B. Gravity
    # Acts on mass. In momentum eq: du/dt = g
    # Lighter fluid rises because the Pressure Gradient (supporting the heavy fluid) 
    # overpowers the weak gravity acting on the light fluid.
    
    # --- 5. Update Velocity ---
    v_new = v_advected + (pressure_accel + GRAVITY) * dt
    
    v_final = diffuse.explicit(v_new, DAMPING, dt)
    r_ng_final = field.where(inflow_mask, 1.5, r_ng_new)
    r_h2_final = field.where(inflow_mask, 0.0, r_h2_new)
   

    return v_final, r_ng_final, r_h2_final

# ============================================================
# 4. RUN SIMULATION
# ============================================================

print("🚀 Running Compressible Euler Simulation...")

v_trj, rng_trj, rh2_trj = iterate(
    euler_step,
    batch(time=STEPS),
    velocity,
    rho_ng,
    rho_h2,
    range=trange
)

# Compute Pressure for visualization
pressure_trj = (rng_trj * C_SQUARED_NG) + (rh2_trj * C_SQUARED_H2)

# ============================================================
# 5. VISUALIZATION
# ============================================================

print("\n📊 Visualizing...")
skip = 10

# 1. Hydrogen Density
plot(rh2_trj.time[::skip], animate='time', title="Hydrogen Density (Compressible)", same_scale=False)
plt.show()

# plot(rng_trj.time[::skip], animate='time', title="Natural Gas Density (Compressible)", same_scale=False)
# plt.show()

# # 2. Pressure Field
# # This is unique to Euler. You will see a "hot spot" of pressure at the injector
# # that pushes waves outward.
# plot(pressure_trj.time[::skip], animate='time', title="Pressure Field (Pa)", same_scale=False)
# plt.show()

# plot(rh2_trj.time[::skip]/(rng_trj.time[::skip] + rh2_trj.time[::skip] + 1e-4), animate='time', title="Hydrogen Mass Fraction", same_scale=False)
# plt.show()