# --- Domain & Simulation ---
# (From your old config, nested)
domain:
  size_x: 100
  size_y: 100
resolution:
  x: 128
  y: 128
dt: 0.8

simulation:
  num_simulations: 50
  total_steps: 50
  save_interval: 1

# --- Data Config ---
# (Nested from old 'output_data' and new 'data_config')
data_config:
  data_dir: "data/"
  dset_name: "smoke_128"
  # Note: "Velocity" is corrected to "velocity"
  data_loader_fields: ["density", "velocity", "inflow"]

# --- PDE Params (for data generation) ---
pde_params:
  batch_size: 1
  nu: 0.0
  buoyancy: 1.0
  inflow_radius: 10.0
  inflow_rate: 0.1 
  inflow_rand_x_range: [0.2, 0.6]
  inflow_rand_y_range: [0.15, 0.05]

# --- Training Config ---
# (From your train_unet.py script)
learning_rate: 1.0e-4
batch_size: 8
epochs: 50
num_predict_steps: 8 # Autoregressive rollout length

# --- Model Config ---
# (From your train_unet.py script)
model_path: "results/models"
model_name: "smoke_128_unet_autoregressive"

model:
  input_specs:
    density: 1
    velocity: 2
    inflow: 1
  output_specs:
    density: 1
    velocity: 2
  levels: 4
  filters: 64
  batch_norm: true